# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('duration', models.TimeField()),
                ('trackCount', models.IntegerField()),
                ('releaseDate', models.DateTimeField(blank=True, null=True)),
                ('albumLink', models.TextField(blank=True, null=True)),
                ('albumCoverurl', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('artistLink', models.TextField(blank=True, null=True)),
                ('artistPictureurl', models.TextField(blank=True, null=True)),
                ('albumCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchResultsAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Album')),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Search')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResultsArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Artist')),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Search')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResultsTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Search')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('duration', models.TimeField()),
                ('trackLink', models.TextField(blank=True, null=True)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Album')),
            ],
        ),
        migrations.AddField(
            model_name='searchresultstrack',
            name='track_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Track'),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='track_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Track'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Artist'),
        ),
    ]
