# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20160416_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
