# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20160520_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='numReviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
