# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_trackreview_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)'),
        ),
    ]
